<?php
// $Id$

/**
 * @file
 * Custom functionality for the drh.dk site.
 */

define('DRH_BUILD_TEASER_FRONT', 'teaser_front');
define('DRH_BUILD_TEASER_SIDEBAR', 'teaser_sidebar');

//include_once('drh_core.features.inc');

/* --- HOOKS (CORE) --------------------------------------------------------- */

function drh_core_init() {
  if ('admin' == arg(0) && 'pages' == arg(2)) {
    drupal_add_css(drupal_get_path('module', 'drh_core') .'/styles/drh_core.panels.css');
  }
  if (drupal_is_front_page()) {
    drupal_add_js(drupal_get_path('module', 'drh_core') .'/scripts/front.js');
  }
}

/* --- HOOKS (CTOOLS) ------------------------------------------------------- */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function drh_core_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
  if ($module == 'panels_mini' && $api == 'panels_default') {
    return array('version' => 1);
  }
  if ($module == 'strongarm' && $api == 'strongarm') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function drh_core_ctools_plugin_directory($module, $plugin) {
  if ('panels' == $module && ('layouts' == $plugin || 'styles' == $plugin)) {
    return 'plugins/'. $plugin;
  }
  if ('ctools' == $module && !empty($plugin)) {
    return 'plugins/'. $plugin;
  }
}

/* --- HOOKS (VIEWS) -------------------------------------------------------- */

/**
 * Implementation of hook_views_api().
 */
function drh_core_views_api() {
  return array('api' => 2.0);
}

/* --- HOOKS (CCK) ---------------------------------------------------------- */

/**
 * Implementation of hook_content_build_modes().
 */
// TODO: is this even necessary?
function drh_core_content_build_modes() {
  return array(
    'teaser' => array(
      'title' => t('Frontpage'),
      'build modes' => array(
        DRH_BUILD_TEASER_FRONT => array(
          'title' => t('Frontpage teaser'),
          'views style' => TRUE,
        ),
        DRH_BUILD_TEASER_SIDEBAR => array(
          'title' => t('Sidebar teaser'),
          'views style' => TRUE,
        ),
      ),
    ),
  );
}
